### ISSUE TITLE
HTTPSConnectionPool(host='servicodados.ibge.gov.br', port=443): Max retries exceeded with url: /api/v1/localidades/estados (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1129)')))

### ISSUE THREAD

**Issue by luanjpb** [leogregianin/ibge#5]
Ao fazer uma atualização no container da minha aplicação que utiliza o pacote, passei a receber o seguinte erro:

```
HTTPSConnectionPool(host='servicodados.ibge.gov.br', port=443): Max retries exceeded with url: /api/v1/localidades/estados (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:1129)')))
```
A versão do Python disponível no novo container era a mesma do container antigo, de modo que a única diferença entre os containeres era a versão do OpenSSL.
Após pesquisa descobri que o erro é causado quando o cliente usa Open SSL 3.0  ou superior e tenta se conectar a um servidor que não suporta a RFC 5746 (secure renegotiation), o que é o caso do servidor `servicodados.ibge.gov.br`. Vou realizar uma pull request com a correção necessária.

Fontes:
- [https://github.com/urllib3/urllib3/issues/2653](https://github.com/urllib3/urllib3/issues/2653)
- [https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled/71646353](https://stackoverflow.com/questions/71603314/ssl-error-unsafe-legacy-renegotiation-disabled/71646353)

**Comment by leogregianin** [comment]
@luanjpb Obrigado pela contribuição, vou revisar o mais breve possível.

**Comment by leogregianin** [comment]
@luanjpb PR #6 merged. Obrigado.
